### ISSUE TITLE
Add developer resources to documentation

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt.github.io#4]
Add developer resources to the documentation with:
1.  compatibility matrix from google doc.  modify to:

- just support OS 2.9 (which has Standards 0.2.10) (b/c OS 2.8.x has a different standards version)
- version of open studio works with what versions of gems
similar to https://github.com/NREL/OpenStudio/wiki/OpenStudio-Version-Compatibility-Matrix

2.  release process.  this should include:

- information on how to release extension, articulation and common measure gems as well. (linked to something on open studio?).
- instructions to Link to documentation URLs in release tags
- instructions to update changelogs as new PRs are merged
3. also document that: gems should use openstudio-standard version shipped with OpenStudio to avoid unforeseen consequences (do not include an openstudio-standard dependency in the gemfile)

**Comment by kflemin** [comment]
can also add documentation on generating the Rdocs here.

**Comment by vtnate** [comment]
https://docs.google.com/document/d/1_uJ1Rm_7KVwCGiPmab07mlftnnmbvI-8N3mucYHIbPg/edit

**Comment by vtnate** [comment]
Closed with #18
