### ISSUE TITLE
Update design doc image

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt.github.io#6]
Replace urbanopt image on https://docs.urbanopt.net/doc_files/design_doc.html to list the correct gems.
<img width="517" alt="Screen Shot 2019-11-06 at 6 58 37 PM" src="https://user-images.githubusercontent.com/2205659/68353660-7fbff580-00c7-11ea-94f6-f78b0ea2b1e0.png">

**Comment by nllong** [comment]
Hi @kflemin -- did you assign me so that I would make the change?
