### ISSUE TITLE
DOCUMENTATION: add mapper inheritance documentation

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt.github.io#89]
When a mapper inherits from another, make sure to require that other mapper first.  Urbanopt cannot guarantee the order in which mappers are added (it various based on os) and can trigger errors.

example:  this line: https://github.com/urbanopt/urbanopt-example-geojson-project/blob/develop/mappers/HighEfficiency.rb#L35

relates to this line: https://github.com/urbanopt/urbanopt-example-geojson-project/blob/develop/mappers/HighEfficiency.rb#L41

add documentation and an example to this page: https://docs.urbanopt.net/customization/new_mapper_class.html

**Comment by vtnate** [comment]
This was resolved with #91. Closing it now.
